name: Download My File

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: wget -O my-file.zip "https://cdn.driverscape.com/misc/amd-catalyst-15.7.1-win10-64bit.zip?access_key=1778707270-zeC0zilyDNC25%2BECgMTzZkP1%2BVD%2FP3G4qPhSOmjqGsc%3D"
      
      - name: Split file into 90MB parts
        run: split -b 90m my-file.zip part_
      
      - name: Upload parts as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: file-parts
          path: part_*
