name: Download My File

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: wget -O my-driver.exe "https://www.driverscape.com/files/misc/amd-catalyst-15.7.1-win10-64bit.zip"
      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: my-driver.exe
