name: Download My File

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: wget -O my-driver.exe "https://files2.freedownloadmanager.org/6/latest/fdm_x86_setup.exe"
      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: my-driver.exe
